<?php
    $jobCollection = $this->getJobsCollection();
    $currentDate = strtotime(date('Y/m/d H:i:s'));   
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $fileType = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('sandeep_config/general/allowed_files');
?>

<div class="job-wrapper">
    <ol class="jobs-list">
        <?php foreach($jobCollection AS $job): ?>
            <?php 
                $expireAt = strtotime($job['expire_at']);
                if($job['job_status'] == 1 && ($currentDate < $expireAt)): 
            ?>
                <li class="job-item">
                    <div class="job-designation"><span>Designation:</span> <?php echo $job['job_designation']; ?></div>
                    <div class="job-description"><span>Description:</span> <?php echo $job['job_description']; ?></div>
                    <div class="job-category-id"><span>Job Category:</span><a href="<?php echo $block->getBaseUrl().'careers/category/view/id/'.$job['job_category_id']; ?>" class="action view">
                            <?php echo $this->getCategoryNameById($job['job_category_id']); ?>
                        </a>  </div>
                    <div class="skills"><span>Skills:</span> <?php echo $job['skills']; ?></div>
                    <div class="meta-title"><span>Title:</span> <?php echo $job['meta_title']; ?></div>
                    <!-- <div class="meta-description"><span>Description:</span> <?php echo $job['meta_description']; ?></div> -->
                    <div class="meta-keywords"><span>Keywords:</span> <?php echo $job['meta_keywords']; ?></div> 
                    <div class="actions" > 
                        <a href="<?php echo $block->getBaseUrl().'careers/index/view/id/'.$job['job_id']; ?>" style="margin-right: 10px; " class="action view">
                            <span>View Jobs</span>
                        </a> 
                        <button type="button" class="apply-btn">Apply Now</button>
                        <div class="form" style="display: none;">
                            <div class="jobsform">
                                <form class="" action="<?php echo $block->getBaseUrl().'careers/index/save'; ?>" id="sandeep-gupta-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
                                <!-- <form id="applicationForm" action="save" method="post"  enctype=multipart/form-data> -->
                                    <label for="applied_for">Apply For:</label>
                                    <input type="text" id="applied_for" disabled name="applied_for" value="<?php echo $job['job_designation']; ?>"><br>
                                    <input type="text" id="applied_hiden" hidden name="applied_for" value="<?php echo $job['job_id']; ?>"><br>

                                    <!-- <label for="application_id">Job Id:</label>
                                    <input type="text" id="application_id" disabled value="<?php// echo date('Ymd'); ?>" name="application_id"><br>
                                    <input type="text" id="application_hidden" hidden value="<?php // echo date('Ymd'); ?>" name="application_id"><br> -->

                                    <label for="candidate_name">Name:</label>
                                    <input type="text" id="candidate_name" name="candidate_name">

                                    <label for="candidate_email">Email:</label>
                                    <input type="email" id="candidate_email" name="candidate_email">
                                    <label for="candidate_phone">Phone:</label>
                                    <input type="text" id="candidate_phone" name="candidate_phone" pattern="^[6-9]\d{9}$" required title="Please enter a valid 10-digit Indian mobile number">
                                    <label for="resume_path">Upload Resume:</label><br>
                                    <input type="file" id="resume_path" name="resume_path"><br>
                                     <?php echo 'Allow files Only '. $fileType ?>
                                    <div style="margin-top: 10px;">
                                        <input type="submit" id="submit-btn" value="Submit">
                                    </div>
                                </form>
                            </div>
                        </div>                        
                    </div>                               
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
</div>
<script>
    require(['jquery', 'Magento_Ui/js/modal/confirm'], function($, confirm) {
        $(document).ready(function(){
            $(".apply-btn").click(function(){
                $(this).next(".form").toggle();
            });
        });
    });
</script>