<?php
    $jobCollection = $this->getJobsCollection();
?>

<div class="job-wrapper">
    <ol class="jobs-list">
        <?php foreach($jobCollection AS $job): ?>
            <?php if($job['job_status'] == 1): ?>
                <li class="job-item">
                    <div class="job-designation"><span>Designation:</span> <?php echo $job['job_designation']; ?></div>
                    <div class="job-description"><span>Description:</span> <?php echo $job['job_description']; ?></div>
                    <div class="job-category-id"><span>Job Category:</span><a href="<?php echo $block->getBaseUrl().'careers/category/view/id/'.$job['job_category_id']; ?>" class="action view">
                            <?php echo $this->getCategoryNameById($job['job_category_id']); ?>
                        </a>  </div>
                    <div class="skills"><span>Skills:</span> <?php echo $job['skills']; ?></div>
                    <div class="meta-title"><span>Title:</span> <?php echo $job['meta_title']; ?></div>
                    <!-- <div class="meta-description"><span>Description:</span> <?php echo $job['meta_description']; ?></div> -->
                    <div class="meta-keywords"><span>Keywords:</span> <?php echo $job['meta_keywords']; ?></div> 
                    <div class="actions"> 
                        <a href="<?php echo $block->getBaseUrl().'careers/index/view/id/'.$job['job_id']; ?>" class="action view">
                            <span>View</span>
                        </a> 
                        <button type="button" class="apply-btn">Apply Now</button>
                        <div class="form" style="display: none;">
                            <div class="jobsform">
                                <form id="applicationForm">
                                    <label for="candidate_name">Apply For:</label>
                                    <input type="text" id="candidate_name" disabled name="candidate_name" value="<?php echo $job['job_designation']; ?>"><br>
                                    <label for="applied_for">Job Id:</label>
                                    <input type="text" id="applied_for" disabled value="<?php echo date('Ymd'); ?>" name="applied_for"><br>
                                    <label for="candidate_name">Name:</label>
                                    <input type="text" id="candidate_name" name="candidate_name">
                                    <label for="candidate_email">Email:</label>
                                    <input type="email" id="candidate_email" name="candidate_email">
                                    <label for="candidate_phone">Phone:</label>
                                    <input type="text" id="candidate_phone" name="candidate_phone">
                                    <label for="resume_path">Upload Resume:</label><br>
                                    <input type="file" id="resume_path" name="resume_path"><br>
                                    <div style="margin-top: 10px;">
                                        <input type="submit" id="submit-btn" value="Submit">
                                    </div>
                                </form>
                            </div>
                        </div>                        
                    </div> 

                              
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
</div>
<script>
    require(['jquery', 'Magento_Ui/js/modal/confirm'], function($, confirm) {
        $(document).ready(function(){
            $("#submit-btn").click(function(){
                $(".apply-btn").next(".form").toggle();
            });
        });
    });
</script>