<?php
$job = $this->getSingleData();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$fileType = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('sandeep_config/general/allowed_files');
?>
<?php if($job->getJobId()) : ?>
    <div class="job-wrapper">
        <ol class="jobs-list">
            <?php if($job['job_status'] == 1): ?>
                <li class="job-item">
                    <div class="job-designation"><span>Designation:</span> <?php echo $job['job_designation']; ?></div>
                    <div class="job-description"><span>Description:</span> <?php echo $job['job_description']; ?></div>                    
                    <div class="skills"><span>Skills:</span> <?php echo $job['skills']; ?></div>
                    <div class="meta-title"><span>Title:</span> <?php echo $job['meta_title']; ?></div>
                    <div class="meta-description"><span>Description:</span> <?php echo $job['meta_description']; ?></div>
                    <div class="meta-keywords"><span>Keywords:</span> <?php echo $job['meta_keywords']; ?></div> 
                     <div class="actions">                        
                        <button type="button" class="apply-btn">Apply Now</button>
                        <div class="form" style="display: none;">
                            <div class="jobsform">
                                <form id="applicationForm" action="careers/index/save" method="post">
                                    <label for="candidate_name">Apply For:</label>
                                    <input type="text" id="candidate_name" disabled name="candidate_name" value="<?php echo $job['job_designation']; ?>"><br>
                                    <label for="applied_for">Job Id:</label>
                                    <input type="text" id="applied_for" disabled value="<?php echo date('Ymd'); ?>" name="applied_for"><br>
                                    <label for="candidate_name">Name:</label>
                                    <input type="text" id="candidate_name" name="candidate_name">
                                    <label for="candidate_email">Email:</label>
                                    <input type="email" id="candidate_email" name="candidate_email">
                                    <label for="candidate_phone">Phone:</label>
                                    <input type="text" id="candidate_phone" name="candidate_phone">
                                    <label for="resume_path">Upload Resume:</label><br>
                                    <input type="file" id="resume_path" name="resume_path"><br>
                                    <?php echo 'Allow files Only '. $fileType ?>
                                    <div style="margin-top: 10px;">
                                        <input type="submit" id="submit-btn" value="Submit">
                                    </div>
                                </form>
                            </div>
                        </div>                        
                    </div>    
                    <a href="<?php echo $block->getBaseUrl().'careers/index/index'; ?>" style= "text-align: right" class="action view">
                            <span>Back</span>
                    </a> 
                </li>
            <?php endif; ?>
        </ol>
    </div>   
<?php else : ?>
    <?php echo __('This job does not exist'); ?>
<?php endif; ?>
<script>
    require(['jquery', 'Magento_Ui/js/modal/confirm'], function($, confirm) {
        $(document).ready(function(){
            $(".apply-btn").click(function(){
                $(this).next(".form").toggle();
            });
        });
    });
</script>